[package]
name = "ebooa"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.1.0"
indicatif = { version = "0.17.8", features = ["improved_unicode", "rayon"] }
memmap2 = "0.9.4"
rand = "0.8.5"
rayon = "1.10.0"
rkyv = { version = "0.7.44", features = ["validation"] }
thousands = "0.2.0"
